name: Deployment
on:
    push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Get project code
            uses: actions/checkout@v4

          - name:
            run: npm ci

          - name: Run linter
            run : npm run lint
        
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Get project code
            uses: actions/checkout@v4

          - name:
            run: npm ci

          - name: Run tests
            run : npm run test
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get project code
            uses: actions/checkout@v4

          - name:
            run: npm ci

          - name: Build project
            run : npm run build
          
          - name: Deploy into AWS
            run: echo "Deploying to EC2 instance..."